# Permalinks
#
permalink:           pretty

# Setup
title:               'Computational Anatomy notes'
description:         'Notes on Bayesian segmentation and registration models.'
url:                 'https://balbasty.github.io/computational-anatomy-notes'
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Yaël Balbastre
  url:               https://github.com/balbasty
  email:             y.balbastre@ucl.ac.uk

