# Permalinks
#
permalink:           pretty
relative_permalinks: true

# Setup
title:               'Computational Anatomy notes'
description:         'Notes on Bayesian segmentation and registration models.'
url:                 'https://balbasty.github.io'
baseurl:             'computational-anatomy-notes'
paginate:            5

# About/contact
author:
  name:              Yaël Balbastre
  url:               https://github.com/balbasty
  email:             y.balbastre@ucl.ac.uk

